### ISSUE TITLE
Read Status not changed unless clicked on the item

### ISSUE THREAD

**Issue by KarthikVV24-11-1999** [gcivil-nyu-org/fall24-monday-team4#113]
Read Status of the report items not changed  inside the View Reports modal unless clicked on the item

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1BjQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--07b5e2f69d38b4dbf92a6fc695b8e21ecb8d4b9f/Screen%20Recording%202024-11-21%20at%2011.59.21%E2%80%AFPM.mov)

<img width="1262" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0RjQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--13b689d895aebb0d34e9375362309a1d2e58d431/Screenshot%202024-11-21%20at%2011.58.30%E2%80%AFPM.png" alt="Screenshot 2024-11-21 at 11.58.30 PM.png" />

**Comment by shashankdatta** [comment]
Not a bug, thats a functionality as well, it's more of ensuring acknowledgement of the report by clicking than just opening and marked as read 

But thank you for the feedback

**Comment by KarthikVV24-11-1999** [comment]
Agreed, just pointing out the potential inconsistency between that testing doc and the application, as I was not sure which was the intended functionality by you
Thanks for the clarification though
